DROP TABLE "COMPANY_EMPLOYEE" CASCADE CONSTRAINT PURGE
/
DROP TABLE "EMPLOYEE" CASCADE CONSTRAINT PURGE
/
DROP SEQUENCE EMPLOYEE_SEQ
/
DROP TABLE "COMPANY" CASCADE CONSTRAINT PURGE
/
DROP SEQUENCE COMPANY_SEQ
/