DROP TABLE "EMPLOYEE" CASCADE CONSTRAINT PURGE
/
CREATE TABLE "EMPLOYEE"(
  "ID" NUMBER(20,0) NOT NULL,
  "FIRST_NAME" VARCHAR2(50) NOT NULL,
  "LAST_NAME" VARCHAR2(50) NULL,
  "GENDER" VARCHAR2(1) NOT NULL,
  "BIRTH_DATE" DATE NOT NULL,
  "MOBILE" VARCHAR2(30) NOT NULL,
  "EMAIL" VARCHAR2(50) NOT NULL,
  "HOME_PHONE" VARCHAR2(30) NULL,
  "STREET" VARCHAR2(255) NOT NULL,
  "CITY" VARCHAR2(50) NOT NULL,
  "ZIP" VARCHAR2(10) NOT NULL,
  "STATE" VARCHAR2(30) NULL,
  "HIRE_DATE" DATE NOT NULL,
  "DESCRIPTION" VARCHAR2(255) NULL,
  "CREATED_AT" TIMESTAMP NOT NULL,
  "CREATED_BY" VARCHAR2(50) NOT NULL,
  "UPDATED_AT" TIMESTAMP NOT NULL,
  "UPDATED_BY" VARCHAR2(50) NOT NULL,
  "VERSION" NUMBER(20,0) NOT NULL
)TABLESPACE MASTERSPACE
/
ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("ID")
/
DROP SEQUENCE EMPLOYEE_SEQ
/
CREATE SEQUENCE EMPLOYEE_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999999
NOCYCLE
NOCACHE
ORDER
/
CREATE OR REPLACE TRIGGER EMPLOYEE_TRIG
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
    SELECT EMPLOYEE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
PURGE RECYCLEBIN
/