CREATE TABLE `COMPANY`(
  `ID` BIGINT(20) AUTO_INCREMENT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `DESCRIPTION` VARCHAR(255) NULL,
  `STREET` VARCHAR(255) NOT NULL,
  `CITY` VARCHAR(50) NOT NULL,
  `ZIP` VARCHAR(10) NOT NULL,
  `STATE` VARCHAR(30) NULL,
  `CREATED_AT` TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_AT` TIMESTAMP NOT NULL,
  `UPDATED_BY` VARCHAR(50) NOT NULL,
  `VERSION` BIGINT(20) NOT NULL,
  CONSTRAINT `COMPANY_PK` PRIMARY KEY (`ID`)
)ENGINE=InnoDB CHARACTER SET 'UTF8';
ALTER TABLE `COMPANY` ADD CONSTRAINT `COMPANY_UK` UNIQUE (`NAME`);

CREATE TABLE `EMPLOYEE`(
  `ID` BIGINT(20) AUTO_INCREMENT NOT NULL,
  `FIRST_NAME` VARCHAR(50) NOT NULL,
  `LAST_NAME` VARCHAR(50) NULL,
  `GENDER` VARCHAR(1) NOT NULL,
  `BIRTH_DATE` DATE NOT NULL,
  `MOBILE` VARCHAR(30) NOT NULL,
  `EMAIL` VARCHAR(50) NOT NULL,
  `HOME_PHONE` VARCHAR(30) NULL,
  `STREET` VARCHAR(255) NOT NULL,
  `CITY` VARCHAR(50) NOT NULL,
  `ZIP` VARCHAR(10) NOT NULL,
  `STATE` VARCHAR(30) NULL,
  `HIRE_DATE` DATE NOT NULL,
  `DESCRIPTION` VARCHAR(255) NULL,
  `CREATED_AT` TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_AT` TIMESTAMP NOT NULL,
  `UPDATED_BY` VARCHAR(50) NOT NULL,
  `VERSION` BIGINT(20) NOT NULL,
  CONSTRAINT `EMPLOYEE_PK` PRIMARY KEY (`ID`)
)ENGINE=InnoDB CHARACTER SET 'UTF8';

CREATE TABLE `COMPANY_EMPLOYEE`(
  `COMPANY_ID` BIGINT(20) NOT NULL,
  `EMPLOYEE_ID` BIGINT(20) NOT NULL,
  CONSTRAINT `COMPANY_EMPLOYEE_PK` PRIMARY KEY (`COMPANY_ID`, `EMPLOYEE_ID`)
)ENGINE=InnoDB CHARACTER SET 'UTF8';
ALTER TABLE `COMPANY_EMPLOYEE` ADD CONSTRAINT `COMPANY_EMPLOYEE_COMPANY_FK` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY`(`ID`);
ALTER TABLE `COMPANY_EMPLOYEE` ADD CONSTRAINT `COMPANY_EMPLOYEE_EMPLOYEE_FK` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `EMPLOYEE`(`ID`);